// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.17.3
// source: frequency/frequency.proto

package frequency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WordFrequencyClient is the client API for WordFrequency service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordFrequencyClient interface {
	Calculate(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error)
}

type wordFrequencyClient struct {
	cc grpc.ClientConnInterface
}

func NewWordFrequencyClient(cc grpc.ClientConnInterface) WordFrequencyClient {
	return &wordFrequencyClient{cc}
}

func (c *wordFrequencyClient) Calculate(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error) {
	out := new(OutputResponse)
	err := c.cc.Invoke(ctx, "/word_frequency.WordFrequency/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordFrequencyServer is the server API for WordFrequency service.
// All implementations must embed UnimplementedWordFrequencyServer
// for forward compatibility
type WordFrequencyServer interface {
	Calculate(context.Context, *InputRequest) (*OutputResponse, error)
	mustEmbedUnimplementedWordFrequencyServer()
}

// UnimplementedWordFrequencyServer must be embedded to have forward compatible implementations.
type UnimplementedWordFrequencyServer struct {
}

func (UnimplementedWordFrequencyServer) Calculate(context.Context, *InputRequest) (*OutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedWordFrequencyServer) mustEmbedUnimplementedWordFrequencyServer() {}

// UnsafeWordFrequencyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordFrequencyServer will
// result in compilation errors.
type UnsafeWordFrequencyServer interface {
	mustEmbedUnimplementedWordFrequencyServer()
}

func RegisterWordFrequencyServer(s grpc.ServiceRegistrar, srv WordFrequencyServer) {
	s.RegisterService(&WordFrequency_ServiceDesc, srv)
}

func _WordFrequency_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordFrequencyServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word_frequency.WordFrequency/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordFrequencyServer).Calculate(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordFrequency_ServiceDesc is the grpc.ServiceDesc for WordFrequency service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordFrequency_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "word_frequency.WordFrequency",
	HandlerType: (*WordFrequencyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _WordFrequency_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frequency/frequency.proto",
}
